# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20170916_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='image',
            field=models.URLField(),
        ),
    ]
