# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20170916_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclothing',
            name='imageURL',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myclothing',
            name='productURL',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='imageURL',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='productURL',
            field=models.URLField(max_length=500),
        ),
    ]
