# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20170916_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='image',
            field=models.URLField(),
        ),
    ]
